### ISSUE TITLE
Enabling WP_DEBUG shows a LOT of errors

### ISSUE THREAD

**Issue by cristianraiber** [ColorlibHQ/Mosh#8]
Visible on both the frontend and/or Customizer.

**Comment by codepixar** [comment]
@cristianraiber - I have checked, I don't find any error in my local server using php 7x. I have also checked in  local. Could you please provide screenshot.

http://prntscr.com/l4p8wt
http://prntscr.com/l4p94d

One thing  when the theme download directly from git and install it showing error because of epsilon use as submodule, that why epsilon not download.

Thanks.

**Comment by cristianraiber** [comment]
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/7841556/46794177-f87f4180-cd4f-11e8-84c5-2a87cd18a17c.png">

**Comment by cristianraiber** [comment]
<img width="1558" alt="image" src="https://user-images.githubusercontent.com/7841556/46794205-0af97b00-cd50-11e8-9a66-14573dccdf94.png">
